### PR TITLE
Fixes #44

### LINKED ISSUE #44: Show Luxuries option is not honored if set in cqui_settings_local.sql
Example from cqui_settings_local.sql:
```
INSERT OR REPLACE INTO CQUI_Settings -- Don't touch this line!
  VALUES
      ("CQUI_AutoExpandUnitActions", 0),
      ("CQUI_ProductionQueue", 1),
      ("CQUI_ShowLuxuries", 0),
      ("CQUI_Smartbanner_Districts", 0),
      ("CQUI_TechPopupVisual", 0),
      ("CQUI_TechPopupAudio", 0),
      ("CQUI_WonderBuiltPopupVisual", 0),
      ("CQUI_WonderBuiltPopupAudio", 0),
      ("CQUI_ToggleYieldsOnLoad", 0);
```

When starting a new game, a look at the options will show the CQUI_ShowLuxuries as unchecked.
image

Once a setting is changed in the CQUI Options Menu (even if that setting is NOT the Show Luxuries), the option will be honored and the luxuries will no longer appear in the top panel.

The way this is implemented makes me think something else is wrong and this may not be the only setting affected by this.

### PR DESCRIPTION
**Pull request by Infixo**
Also reformatted for 4 spaces.

### CODE REVIEW

File: Assets/UI/toppanel_CQUI.lua [hunk 1]
```diff
@@ -9,78 +9,71 @@ BASE_CQUI_RefreshResources = RefreshResources;
 -- ===========================================================================
 local CQUI_showLuxury = true;
 
+function CQUI_OnSettingsInitialized()
+	CQUI_showLuxury = GameConfiguration.GetValue("CQUI_ShowLuxuries"); -- Infixo, issue #44
+end
```
Comment (alimulhuda) [inline Assets/UI/toppanel_CQUI.lua:14]: Missed a tab character to space conversion.

File: Assets/UI/toppanel_CQUI.lua [hunk 2]
```diff
@@ -9,78 +9,71 @@ BASE_CQUI_RefreshResources = RefreshResources;
...
-              isOverflow = true;
-            end
-          end
-        end
-      end
-    end
+    if CQUI_showLuxury then
+        for resource in GameInfo.Resources() do
+            if resource.ResourceClassType == "RESOURCECLASS_LUXURY" then -- it cleary says "show luxuries in the top panel"...
+                local amount:number = pPlayerResources:GetResourceAmount(resource.ResourceType);
```
Comment (alimulhuda) [inline Assets/UI/toppanel_CQUI.lua:46]: Unmodded game has a null check for `resource.ResourceClassType`. I'm guessing your removal for that means it was unnecessary, is that right?

Comment (Infixo) [reply Assets/UI/toppanel_CQUI.lua:46]: This field has a NOT NULL constraint in DB. It cannot be nil.
